name: Auto Assign Reviewers
on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Assign Reviewers
        uses: kentaro-m/auto-assign-action@v1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/auto_assign.yml
