name: Auto Assign Reviewers
on:
  pull_request:
    types: [opened]

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Reviewers
        uses: kentaro-m/auto-assign-action@v1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: jbustillolorenzo, jeimigarcia, mariolopezserrano96, yiramirez
          team-reviewers: renfe-nsv-devops
          number-of-reviewers: 2
